### PR TITLE
Update rococo-v1

### LINKED ISSUE #60: Update to latest rococo-v1
The Cumulus workshop contains Polkadot chain specs that need to be updated to the specified commits at the same time as the docs.

### PR DESCRIPTION
**Pull request by NukeManDan**
Commits:

- **Polkadot @ [`127eb17a`](https://github.com/paritytech/polkadot/commit/127eb17a25bbe2a9f2731ff11a65d7f8170f2373)**
- **Parachain Template @ [`1e1e725`](https://github.com/substrate-developer-hub/substrate-parachain-template/commit/1e1e7257e4429e8413f5a27940d4941d220317a7)**
- **Polkadot JS Apps @ [`35b238a `](https://github.com/polkadot-js/apps/commit/35b238a1bfb59a4c4e7488671a7261b54bf314c9)** (hosted apps v0.90.2-14 working as well)

Closes #60 

- [x] Validate that all relay **raw** chain specs provided are acepted with relay chain to startup
- [x] Confirm relay chain validator blocks are being produced 
- [x] Register parachain template to relay
- [x] Confirm parachain collator blocks are being produced 
- [x] Submit extrinsics from parachain 200

### CODE REVIEW

**Comment by NukeManDan** [comment]
When going plain -> raw chainspec, I get this error (or warning?):
```
./target/release/polkadot build-spec --chain rococo-custom-plain.json --raw --disable-default-bootnode > rococo-custom.json
2021-05-05 22:53:32  Building chain spec    
2021-05-05 22:53:35  Took active validators from set with wrong size    
2021-05-05 22:53:35  Took active validators from set with wrong size   
```

**Comment by NukeManDan** [comment]
ready for review, but per my comment, I still get a weird warning. Any ideas on what this is from?

All tesets marked ✅  in first comment are complete.

**Comment by al3mart** [comment]
> When going plain -> raw chain spec, I get this error (or warning?):
> 
> ```
> ./target/release/polkadot build-spec --chain rococo-custom-plain.json --raw --disable-default-bootnode > rococo-custom.json
> 2021-05-05 22:53:32  Building chain spec    
> 2021-05-05 22:53:35  Took active validators from set with wrong size    
> 2021-05-05 22:53:35  Took active validators from set with wrong size   
> ```

I have run into the same issue, that message is prompted but the result works fine.
You can see it happen [here](https://github.com/paritytech/polkadot-launch/issues/90) too

**Review by riusricardo — APPROVED** [review]
LGTM 👍
Thanks for making the update.

**Comment by riusricardo** [comment]
Please update the Polkadot and Template commits in this file:
https://www.github.com/substrate-developer-hub/cumulus-workshop/tree/5b0412178b306596755c799cae201b7afb883e5e/en%2F1-prep%2F1-compiling.md

**Review by al3mart — APPROVED** [review]
Looks good

**Pull request merged**
