### PR TITLE
Update to v0.9.10

### PR DESCRIPTION
**Pull request by NukeManDan**
- [x] Update template https://github.com/substrate-developer-hub/substrate-parachain-template/pull/73
- [x] Include new chainspec files
- [x] Test & check for inconsistencies in docs/snippets
- [x] Conclusion on fix for https://github.com/paritytech/substrate/issues/9827 or a note to ignore the libp2p warnings in the logs

### CODE REVIEW

**Comment by NukeManDan** [comment]
@jimmychu0807 I have attempted to get  `polkadot-launch` working, but failed to do so. I am trying to run with a locally build version of the tool, and copied over the bins from the builds into the same temporary folder as my config file.

Can you check that there is no breaking changes somehow here, as you kindly added this content :pray: - if it's just me, let's merge this. If not, let's fix it.

**Comment by jimmychu0807** [comment]
Thanks for the update. I will take a look at this tmr. Testing relay-chain and parachain-template takes some time.

**Review by riusricardo — APPROVED** [review]

**Comment by jimmychu0807** [comment]
@NukeManDan I will test the polkadot-launch issue and apply fixes. But I am thinking of not applying fixes in this repo but on substrate-docs. Is this okay with you?

**Comment by NukeManDan** [comment]
That's fine, just @ me @jimmychu0807 so I can integrate it into https://github.com/substrate-developer-hub/substrate-docs/pull/203

**Comment by jimmychu0807** [comment]
@NukeManDan Are you running `master` branch of polkadot-launch. I tried with the latest release v1.7.0 (not master) of polkadot launch. 

There is an update that we no longer need the `--force-authoring` flag in parachains node flags. With that, I am able to kickstart the relay-chain parachain-chain network locally with polkadot-launch.

**Pull request merged**
